export const REQUEST_QUESTIONS = 'REQUEST_QUESTIONS';
export const RECEIVE_QUESTIONS = 'RECEIVE_QUESTIONS';
export const REJECT_QUESTIONS = 'REJECT_QUESTIONS';
export const SELECT_ANSWER = 'SELECT_ANSWER';
